General:
    Modus:         Collider
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      50.0
    Randomseed:    -1
    Testparticles: 1
    Nevents:       20000
    Gaussian_Sigma: 1.0
    Gauss_Cutoff_In_Sigma: 3.0
    Use_Grid: True

Output:
    Output_Interval:  1.0
    Density_Type:      "none"
    Particles:
            Format:          ["Oscar2013"]
            Extended:        False
            Only_Final:      True

Collision_Term:
    Two_to_One:             True
    Strings:                True
    Force_Decays_At_End:    True
    Strings_with_Probability: True
    String_Parameters:
        Leading_Frag_Mean: 1.0
        Leading_Frag_Width: 0.6
        StringZ_B: 0.3
        Strange_Supp: 0.12
        Diquark_Supp: 0.03
        String_Sigma_T: 0.38
        Sigma_Perp: 0.6
Modi:
    Collider:
        Projectile:
            Particles: {2212: 1, 2112: 0}  # Proton
            Automatic: true
            Deformed: false
        Target:
            Particles: {2212: 1, 2112: 0}  # Proton
            Automatic: true
            Deformed: false
        Calculation_Frame: "center of mass"
        Impact:
            Value: 0.0
        Fermi_Motion: "off"
